name: Feature suggestion
description: Suggest a non-existant feature
title: "[Feature suggestion]"
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping me, making this application better!
        Please note, that it may take time until I answer since I am not on GitHub 24/7
  - type: textarea
    id: featuredescription
    attributes:
      label: Describe the Feature
      description: |
        A clear and concise description of what the Feature is.
    validations:
      required: true