name: Feature Request
description: Request a new feature
title: "[Feature request]"
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making Qwotable better and requesting new features.
  - type: textarea
    id: featuredescription
    attributes:
      label: Describe the feature you'd like to have in detail
      description: |
      A clear and concise description of what you want to have.
    validations:
      required: true
  - type: textarea
    id: additionalcontext
    attributes:
      label: Additional information
      description: |
      Add any other context or screenshots about the feature request here.
    validations:
      required: false