name: Get App Metadata

on: [push]

jobs:
  get_metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Validate Fastlane Supply Metadata
      uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2

